"""Recreate messages table

Revision ID: 940400ce5a18
Revises: 9630f5ee513d
Create Date: 2025-06-23 03:14:06.017062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940400ce5a18'
down_revision = '9630f5ee513d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
